<?php
	include_once("db.php");
	include_once("settings.php");
	include_once("functions.php");
	include_once("functionRegister.php");
	include_once("functionLogin.php");
	include_once("functionReport.php");
	include_once("functionSearch.php");
	include_once("recoverPass.php");
	include_once("searchUser.php");
	include_once("searchVehicle.php");
?>